### ISSUE TITLE
Update bulk upload history table with new feature to re-process file 

### ISSUE THREAD

**Issue by janithRS** [moe-lk/sis-php#106]
Update the bulk upload table with a new feature enabling re-process the data file if the state is pending (Not processed).

**Comment by nshamit** [comment]
#91

**Comment by mohamednizar** [comment]
https://github.com/moe-lk/bulk-upload/pull/112  is contained the solution for this.

**Comment by mohamednizar** [comment]
@jeewana20 , The solution is deployed to the dev, please comment if any changes needed.

**Comment by resha007** [comment]
no buttons appear in history.
![history error](https://user-images.githubusercontent.com/45994536/73153184-ce928f80-40f8-11ea-849d-48474af8db08.PNG)

**Comment by janithRS** [comment]
Fixed in the latest commit. Will be available in the dev shortly

**Comment by resha007** [comment]
is bulk upload - dev working?

**Comment by resha007** [comment]
no emails received yet.pending for email status.
![no emails](https://user-images.githubusercontent.com/45994536/73511006-22a7b780-440a-11ea-9c37-fb7994911f44.PNG)

**Comment by mohamednizar** [comment]
@jeewana20 , @nshamit , the email function for this issue is committed , but the cronjob is not yet enabed in the stag. Ref email issue in dev, we on debugging progress still not encountered the reason for this.

**Comment by resha007** [comment]
any update in this issue?
