### ISSUE TITLE
Help is not working

### ISSUE THREAD

**Issue by jeewana20** [moe-lk/sis-php#128]
help in the system cant be accessible. its showing 404 error.
![404 error help](https://user-images.githubusercontent.com/55229512/73816387-849f5d00-480e-11ea-9101-67cc370de640.PNG)

**Comment by janithRS** [comment]
Fixed #129

**Comment by resha007** [comment]
help is still not working

**Comment by janithRS** [comment]
Please clear the cache and try again. It is working on the dev.

**Comment by resha007** [comment]
we tried with several machines with several browsers. it is worked fine in dev, but the prod, error remains.

**Comment by janithRS** [comment]
Yes. Prod is to be updated

**Comment by resha007** [comment]
help is still not working.

**Comment by jeewana20** [comment]
now its working.
